version: "3"

services:
  freeswitch:
    build:
      context: ../services/freeswitch
      dockerfile: ./Dockerfile
    network_mode: host
    restart: always

  frontend:
    build:
      context: ../services/frontend
      dockerfile: ./Dockerfile
      args:
        - SIP_SERVER_IP
    network_mode: host
    env_file:
      - .env
    restart: always