version: "3"

services:
  freeswitch:
    build:
      context: ../services/freeswitch
      dockerfile: ./Dockerfile
      args:
        - SIP_PASSWORD
    network_mode: host
    restart: always

  frontend:
    build:
      context: ../services/frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_SIP_SERVER_IP
        - VITE_SIP_SERVER_URL
        - SERVER_IP
    network_mode: host
    env_file:
      - ../services/frontend/.env
    restart: always